#!/bin/bash

echo "=========================================="
echo "SDN Traffic Testing Commands"
echo "=========================================="
echo ""
echo "Run these commands in Mininet CLI:"
echo ""
echo "# Test connectivity"
echo "mininet> pingall"
echo ""
echo "# Generate HTTP traffic"
echo "mininet> h1 python3 utils/traffic_generator.py 10.0.0.1 10.0.0.3 http &"
echo ""
echo "# Generate Video traffic"
echo "mininet> h2 python3 utils/traffic_generator.py 10.0.0.2 10.0.0.4 video &"
echo ""
echo "# Generate VoIP traffic"
echo "mininet> h3 python3 utils/traffic_generator.py 10.0.0.3 10.0.0.5 voip &"
echo ""
echo "# Generate Gaming traffic"
echo "mininet> h4 python3 utils/traffic_generator.py 10.0.0.4 10.0.0.6 gaming &"
echo ""
echo "# Generate FTP traffic"
echo "mininet> h5 python3 utils/traffic_generator.py 10.0.0.5 10.0.0.1 ftp &"
echo ""
echo "# Check flow tables"
echo "sudo ovs-ofctl dump-flows s1 -O OpenFlow13"
echo ""
echo "# Test bandwidth"
echo "mininet> iperf h1 h3"
echo ""
echo "# Test latency"
echo "mininet> h1 ping -c 10 h3"
echo ""
echo "=========================================="